licenses(["notice"])

java_binary(
    name = "hasher",
    main_class = "rules.jvm.external.Hasher",
    runtime_deps = ["//private/tools/java/rules/jvm/external:hasher"],
)

java_binary(
    name = "bom_parser",
    main_class = "rules.jvm.external.MavenBomParser",
    runtime_deps = ["//private/tools/java/rules/jvm/external:bom_parser"],
)